/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;
///import bean.Ordendecompra;
import bean.Articulo;
import bean.AuditoriaSistema;
import bean.DetalleFacturacompra;
import bean.DetalleOrdenCompra;
import bean.FacturaPago;
import bean.Informerecepcion;
import bean.OrdenCompra;
import bean.Proveedor;
import bean.TablaOrdenCompra;
import java.awt.EventQueue;
import java.beans.Beans;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author tammy
 */
public class InformeRecepcionVisualizar extends javax.swing.JFrame {
private char ch;
    private int resp;
  private int id, k;
  private int fila;
  private String numero;
   private int codigo, precio, cantidadPedida, cantidadRecibida, i,  valor;
  private String nombreArticulo;
private static int totalCompra = 0, totaliva=0;
 private int id1,id2;

  private int codInf, codOc, nroFac;
  private String fecha, usuario, fechavto;
    /**
     * Creates new form InfoRecepcion
     */
    public InformeRecepcionVisualizar() {
       initComponents();
       txtIva.setText("0");
       txt_total.setText("0");
        tf_oc.setEnabled(false);
      // txt_num1.setEnabled(false);
     //  txt_num2.setEnabled(false);
       txt_num3.setEnabled(false);
       tf_proveedor.setEnabled(false);
       jf_fechaI.setVisible(false);
       jf_fechaF.setVisible(false);
       txt_num1.setVisible(false);
       txt_num2.setVisible(false);
       tf_fechaFact.setEnabled(false);
       tf_fechaVto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("proyectoPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT i FROM Informerecepcion i");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        facturaPagoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM FacturaPago f");
        facturaPagoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : facturaPagoQuery.getResultList();
        ordenCompraQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT o FROM OrdenCompra o");
        ordenCompraList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(ordenCompraQuery.getResultList());
        detalleOrdenCompraQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DetalleOrdenCompra d");
        detalleOrdenCompraList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(detalleOrdenCompraQuery.getResultList());
        jPanel1 = new javax.swing.JPanel();
        lbl_oc = new javax.swing.JLabel();
        tf_oc = new javax.swing.JTextField();
        lbl_oc1 = new javax.swing.JLabel();
        txt_num1 = new javax.swing.JTextField();
        txt_num2 = new javax.swing.JTextField();
        txt_num3 = new javax.swing.JTextField();
        lbl_oc2 = new javax.swing.JLabel();
        lbl_oc3 = new javax.swing.JLabel();
        jf_fechaI = new com.toedter.calendar.JDateChooser();
        jf_fechaF = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompra = new javax.swing.JTable();
        txtIva = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        tf_proveedor = new javax.swing.JTextField();
        lbl_oc4 = new javax.swing.JLabel();
        tf_fechaVto = new javax.swing.JTextField();
        tf_fechaFact = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btn_cancelar3 = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_registrarC = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_valor = new javax.swing.JLabel();
        tf_valor = new javax.swing.JTextField();
        lbl_filtro = new javax.swing.JLabel();
        list_filtros = new javax.swing.JComboBox();
        btn_buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_oc.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lbl_oc.setText("Nro. Orden Compra: ");

        tf_oc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ocActionPerformed(evt);
            }
        });
        tf_oc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_ocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_ocFocusLost(evt);
            }
        });
        tf_oc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_ocKeyTyped(evt);
            }
        });

        lbl_oc1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lbl_oc1.setText("Nro. Factura Compra: ");

        txt_num1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_num1KeyTyped(evt);
            }
        });

        txt_num2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_num2KeyTyped(evt);
            }
        });

        txt_num3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_num3FocusLost(evt);
            }
        });
        txt_num3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_num3KeyTyped(evt);
            }
        });

        lbl_oc2.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lbl_oc2.setText("Fecha Factura: ");

        lbl_oc3.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lbl_oc3.setText("Fecha Vto. Factura: ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Detalle Compra", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        tablaCompra.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        tablaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Precio", "Cantidad Pedida", "Cantidad Recibida", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCompra);

        txtIva.setEnabled(false);
        txtIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIvaActionPerformed(evt);
            }
        });

        jLabel1.setText("Total I.V.A:");

        jLabel3.setText("Total:");

        txt_total.setEditable(false);
        txt_total.setEnabled(false);
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)))
        );

        tf_proveedor.setEnabled(false);
        tf_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_proveedorActionPerformed(evt);
            }
        });
        tf_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_proveedorKeyTyped(evt);
            }
        });

        lbl_oc4.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lbl_oc4.setText("Proveedor");

        tf_fechaVto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_fechaVtoActionPerformed(evt);
            }
        });

        tf_fechaFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_fechaFactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_oc)
                            .addComponent(lbl_oc1)
                            .addComponent(lbl_oc2)
                            .addComponent(lbl_oc3)
                            .addComponent(lbl_oc4))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_oc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_num2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_num3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_fechaFact, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jf_fechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_fechaVto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jf_fechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_oc)
                    .addComponent(tf_oc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_oc1)
                    .addComponent(txt_num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_num3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_oc2)
                        .addComponent(tf_fechaFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jf_fechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_oc3)
                            .addComponent(tf_fechaVto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_oc4)
                            .addComponent(tf_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jf_fechaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_cancelar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        btn_cancelar3.setText("Cancelar");
        btn_cancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar3ActionPerformed(evt);
            }
        });

        btn_imprimir.setText("Imprimir");
        btn_imprimir.setEnabled(false);
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(btn_imprimir)
                .addGap(26, 26, 26)
                .addComponent(btn_cancelar3)
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar3)
                    .addComponent(btn_imprimir))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_registrarC.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        lbl_registrarC.setForeground(new java.awt.Color(255, 255, 255));
        lbl_registrarC.setText("Informe de Recepcion ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(lbl_registrarC)
                .addGap(184, 184, 184))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_registrarC)
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_valor.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lbl_valor.setText("Valor:");

        tf_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_valorKeyTyped(evt);
            }
        });

        lbl_filtro.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lbl_filtro.setText("Buscar por:");

        list_filtros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo Informe", "Codigo Orden Compra", "Proveedor" }));
        list_filtros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_filtrosMouseClicked(evt);
            }
        });

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        btn_buscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_buscarFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbl_filtro)
                .addGap(18, 18, 18)
                .addComponent(list_filtros, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(lbl_valor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar)
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_filtro)
                    .addComponent(list_filtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_valor)
                    .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addContainerGap())
        );

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, tabla);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codInformeRecepcion}"));
        columnBinding.setColumnName("Cod Informe Recepcion");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codOC}"));
        columnBinding.setColumnName("Cod OC");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fecha}"));
        columnBinding.setColumnName("Fecha");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fechaVto}"));
        columnBinding.setColumnName("Fecha Vto");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nroFactura}"));
        columnBinding.setColumnName("Nro Factura");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(364, 364, 364))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_ocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_ocKeyTyped
        // TODO add your handling code here:
        int limite=4;
        if(tf_oc.getText().length()==limite){
            getToolkit().beep();
            evt.consume(); //se le ignora

        }
        ch=evt.getKeyChar();
        if(!Character.isDigit(ch)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_tf_ocKeyTyped

    private void tf_ocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ocActionPerformed

    private void txt_num1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_num1KeyTyped
        // TODO add your handling code here:
        int limite=3;
        if(txt_num1.getText().length()==limite){
            getToolkit().beep();
            evt.consume(); //se le ignora

        }
        ch=evt.getKeyChar();
        if(!Character.isDigit(ch)){
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_txt_num1KeyTyped

    private void txt_num2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_num2KeyTyped
        // TODO add your handling code here:
        int limite=3;
        if(txt_num2.getText().length()==limite){
            getToolkit().beep();
            evt.consume(); //se le ignora

        }
        ch=evt.getKeyChar();
        if(!Character.isDigit(ch)){
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_txt_num2KeyTyped

    private void txt_num3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_num3KeyTyped
        // TODO add your handling code here:
        int limite=5;
        if(txt_num3.getText().length()==limite){
            getToolkit().beep();
            evt.consume(); //se le ignora

        }
        ch=evt.getKeyChar();
        if(!Character.isDigit(ch)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_num3KeyTyped

    private void btn_cancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelar3ActionPerformed

    private void txtIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIvaActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void tf_proveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_proveedorKeyTyped
        // TODO add your handling code here:
        ch=evt.getKeyChar();
        if(Character.isDigit(ch)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_tf_proveedorKeyTyped

    private void tf_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_proveedorActionPerformed

    private void tf_valorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_valorKeyTyped
        // TODO add your handling code here:
        if(list_filtros.getSelectedItem()=="Proveedor" ){
            ch=evt.getKeyChar();
            if(Character.isDigit(ch)){
                getToolkit().beep();
                evt.consume();
            }
        }else{
            if(list_filtros.getSelectedItem()=="Codigo Informe"){
                ch=evt.getKeyChar();
                if(!Character.isDigit(ch)){
                    getToolkit().beep();
                    evt.consume();
                }
                if(list_filtros.getSelectedItem()=="Codigo Orden Compra"){
                    ch=evt.getKeyChar();
                    if(!Character.isDigit(ch)){
                        getToolkit().beep();
                        evt.consume();
                    }

                }}
            }
    }//GEN-LAST:event_tf_valorKeyTyped

    private void list_filtrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_filtrosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_list_filtrosMouseClicked

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        if (tf_valor.getText().length()==0){
            JOptionPane.showMessageDialog(null,"Ingrese algún valor para efectuar la búsqueda", "Advertencia",JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            if(list_filtros.getSelectedItem()=="Codigo Informe"){
                id1=Integer.parseInt(tf_valor.getText());
                query=entityManager.createNamedQuery( "Informerecepcion.findByCodInformeRecepcion");
                query.setParameter("codInformeRecepcion", id1);
                List<Informerecepcion> a=query.getResultList();
                if (a.isEmpty()){
                    JOptionPane.showMessageDialog(null,"Código inexistente", "Error",JOptionPane.ERROR_MESSAGE);
                    tf_valor.setText(null);
                    return;
                }
                list.clear();
                list.addAll(a);

            }
            if(list_filtros.getSelectedItem()=="Codigo Orden Compra"){
                id2=Integer.parseInt(tf_valor.getText());
                query=entityManager.createNamedQuery( "Informerecepcion.findByCodOC");
                query.setParameter("codOC", id2);
                List<Informerecepcion> a=query.getResultList();
                if (a.isEmpty()){
                    JOptionPane.showMessageDialog(null,"Código inexistente", "Error",JOptionPane.ERROR_MESSAGE);
                    tf_valor.setText(null);
                    return;
                }
                list.clear();
                list.addAll(a);

            }
            if (list_filtros.getSelectedItem()=="Proveedor"){
                query = entityManager.createNativeQuery("select * from informerecepcion inf" +
                    " join orden_compra oc" +
                    " on inf.codOC=oc.cod_orden" +
                    " join proveedor p" +
                    " on p.codigoProveedor=oc.cod_proveedor"+
                    " where p.razonSocial like "+
                    "'%"+tf_valor.getText()+"%'", Informerecepcion.class);
                List<Informerecepcion> ar = query.getResultList();
                if (ar.size()==0){
                    JOptionPane.showMessageDialog(null," Nombre Proveedor Inexistente", "Error",JOptionPane.ERROR_MESSAGE);
                    tf_valor.setText(null);
                    return;
                }
                list.clear();
                list.addAll(ar);
            }
        }

        //        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_buscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_buscarFocusLost
        // TODO add your handling code here:
        tf_valor.setText(null);
    }//GEN-LAST:event_btn_buscarFocusLost

    private void tf_fechaVtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_fechaVtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_fechaVtoActionPerformed

    private void tf_fechaFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_fechaFactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_fechaFactActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        btn_imprimir.setEnabled(true);
        vaciar_tabla_factura_compra();
        tf_oc.setEnabled(false);
        // txt_num1.setEnabled(false);
        //  txt_num2.setEnabled(false);
        txt_num3.setEnabled(false);
        tf_proveedor.setEnabled(false);
        jf_fechaI.setVisible(false);
        jf_fechaF.setVisible(false);
        txt_num1.setVisible(false);
        txt_num2.setVisible(false);
        tf_fechaFact.setVisible(true);
        tf_fechaVto.setVisible(true);
//        btn_eliminar.setEnabled(true);

        fila=tabla.getSelectedRow();
        codigo=(Integer) tabla.getValueAt(fila, 1);
        codInf= (Integer) tabla.getValueAt(fila, 0);
        nroFac=(Integer) tabla.getValueAt(fila, 4);
        fecha=(String) tabla.getValueAt(fila, 2);
        fechavto=(String) tabla.getValueAt(fila, 3);
        tf_oc.setText(Integer.toString(codigo));

        txt_num3.setText(Integer.toString(nroFac));
        tf_fechaFact.setText(fecha);
        tf_fechaVto.setText(fechavto);

        OrdenCompra tc=(OrdenCompra) obtenerDetalle(codigo) ;
        Proveedor p= obtenerProveedor1(tc.getCodProveedor().getCodigoProveedor());
        tf_proveedor.setText(p.getRazonSocial());
        registarFacturaDetalle();
    }//GEN-LAST:event_tablaMouseClicked

    private void tf_ocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_ocFocusLost
        // TODO add your handling code here:
                id=Integer.parseInt(tf_oc.getText());
        ordenCompraQuery=entityManager.createNamedQuery( "OrdenCompra.findByCodOrden");
        ordenCompraQuery.setParameter("codOrden", id);
                List<OrdenCompra> oc=ordenCompraQuery.getResultList();
                if (oc.isEmpty()){
                    JOptionPane.showMessageDialog(null,"Código de orden de compra inexistente", "Error",JOptionPane.ERROR_MESSAGE);
                    tf_oc.setText(null);
                    vaciar();
                    return;
                }
          query = entityManager.createNamedQuery("Informerecepcion.findByCodOC");
                query.setParameter("codOC", Integer.parseInt(tf_oc.getText()));
                List<Informerecepcion> inf= query.getResultList();
                if (inf.size()!=0){
                    JOptionPane.showMessageDialog(null,"Ya se registro el informe ", "Error",JOptionPane.ERROR_MESSAGE);
                    tf_oc.setText(null);
                    vaciar();
                    return;
                }

       
        
    }//GEN-LAST:event_tf_ocFocusLost

    private void tf_ocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_ocFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_tf_ocFocusGained

    private void txt_num3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_num3FocusLost
        // TODO add your handling code here:
         numero = (txt_num1.getText()+txt_num2.getText()+txt_num3.getText()).toLowerCase();
         query = entityManager.createNamedQuery("Informerecepcion.findByNroFactura");
                query.setParameter("nroFactura", Integer.parseInt(numero));
                List<Informerecepcion> inf1= query.getResultList();
                if (inf1.size()!=0){
                    JOptionPane.showMessageDialog(null,"Ya se registro el informe ", "Error",JOptionPane.ERROR_MESSAGE);
                    txt_num1.setText(null);
                    txt_num2.setText(null);
                    txt_num3.setText(null);
                    vaciar();
                    return;
                }
 
    }//GEN-LAST:event_txt_num3FocusLost

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        // TODO add your handling code here:
        imprimir(Integer.valueOf(txt_num3.getText()));
    }//GEN-LAST:event_btn_imprimirActionPerformed

private OrdenCompra obtenerDetalle(int cod){
        EntityManagerFactory fact = Persistence.createEntityManagerFactory("proyectoPU");
        EntityManager ema = fact.createEntityManager();
        Query query = ema.createNamedQuery("OrdenCompra.findByCodOrden");
        query.setParameter("codOrden", cod);
        List<OrdenCompra> pro = query.getResultList();
        OrdenCompra prodServ = null;
        try{
            prodServ = pro.get(0);
        }catch(ArrayIndexOutOfBoundsException e){
            System.out.println(e);
        }catch(NullPointerException e){
            System.out.println(e);
        }catch(Exception e){
            System.out.println("Algo pasó");
        }
        
        ema.close();
        return prodServ;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeRecepcionVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeRecepcionVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeRecepcionVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeRecepcionVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoRecepcion().setVisible(true);
            }
        });*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame=new InformeRecepcionVisualizar();
                frame.setVisible(true);
                frame.setTitle("Informe recepcion");
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar3;
    private javax.swing.JButton btn_imprimir;
    private java.util.List<bean.DetalleOrdenCompra> detalleOrdenCompraList;
    private javax.persistence.Query detalleOrdenCompraQuery;
    private javax.persistence.EntityManager entityManager;
    private java.util.List<bean.FacturaPago> facturaPagoList;
    private javax.persistence.Query facturaPagoQuery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static com.toedter.calendar.JDateChooser jf_fechaF;
    private static com.toedter.calendar.JDateChooser jf_fechaI;
    private javax.swing.JLabel lbl_filtro;
    private javax.swing.JLabel lbl_oc;
    private javax.swing.JLabel lbl_oc1;
    private javax.swing.JLabel lbl_oc2;
    private javax.swing.JLabel lbl_oc3;
    private javax.swing.JLabel lbl_oc4;
    private javax.swing.JLabel lbl_registrarC;
    private javax.swing.JLabel lbl_valor;
    private java.util.List<bean.Informerecepcion> list;
    private javax.swing.JComboBox list_filtros;
    private java.util.List<bean.OrdenCompra> ordenCompraList;
    private javax.persistence.Query ordenCompraQuery;
    private javax.persistence.Query query;
    private javax.swing.JTable tabla;
    private static javax.swing.JTable tablaCompra;
    private javax.swing.JTextField tf_fechaFact;
    private javax.swing.JTextField tf_fechaVto;
    public static javax.swing.JTextField tf_oc;
    private static javax.swing.JTextField tf_proveedor;
    private javax.swing.JTextField tf_valor;
    private static javax.swing.JTextField txtIva;
    private static javax.swing.JTextField txt_num1;
    private static javax.swing.JTextField txt_num2;
    private static javax.swing.JTextField txt_num3;
    private static javax.swing.JTextField txt_total;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

private Proveedor obtenerProveedor1(int cod){
        EntityManagerFactory fact = Persistence.createEntityManagerFactory("proyectoPU");
        EntityManager ema = fact.createEntityManager();
        Query query = ema.createNamedQuery("Proveedor.findByCodigoProveedor");
        query.setParameter("codigoProveedor", cod);
        List<Proveedor> p = query.getResultList();
        Proveedor nom = null;
        try{
            nom = p.get(0);
        }catch(ArrayIndexOutOfBoundsException e){
            System.out.println(e);
        }catch(NullPointerException e){
            System.out.println(e);
        }catch(Exception e){
            System.out.println("Algo pasó");
        }
        
        ema.close();
        return nom;
    }
 
private DetalleOrdenCompra obtenerArticulos(int oc){
        EntityManagerFactory fact = Persistence.createEntityManagerFactory("proyectoPU");
        EntityManager ema = fact.createEntityManager();
        Query query = ema.createNamedQuery("DetalleOrdenCompra.findByCodDetalle");
        query.setParameter("codDetalle",oc);
        List<DetalleOrdenCompra> a = query.getResultList();
        DetalleOrdenCompra nom = null;
        try{
            nom = a.get(0);
        }catch(ArrayIndexOutOfBoundsException e){
            System.out.println(e);
        }catch(NullPointerException e){
            System.out.println(e);
        }catch(Exception e){
            System.out.println("Algo pasó");
        }
        
        ema.close();
        return nom;
    }
private DetalleFacturacompra obtenerDetalleFactura(int fac){
        EntityManagerFactory fact = Persistence.createEntityManagerFactory("proyectoPU");
        EntityManager ema = fact.createEntityManager();
        Query query = ema.createNamedQuery("DetalleFacturacompra.findByNumFactura");
        query.setParameter("numFactura",fac);
        List<DetalleFacturacompra> a = query.getResultList();
        DetalleFacturacompra nom = null;
        try{
            nom = a.get(0);
        }catch(ArrayIndexOutOfBoundsException e){
            System.out.println(e);
        }catch(NullPointerException e){
            System.out.println(e);
        }catch(Exception e){
            System.out.println("Algo pasó");
        }
        
        ema.close();
        return nom;
    }

    private void registarFacturaDetalle() {
   detalleOrdenCompraQuery=entityManager.createNamedQuery( "DetalleOrdenCompra.findByCodOrden");
                detalleOrdenCompraQuery.setParameter("codOrden", Integer.valueOf(tf_oc.getText()));
                List<DetalleOrdenCompra> oc=detalleOrdenCompraQuery.getResultList();
                if (oc.isEmpty()){
                    JOptionPane.showMessageDialog(null,"no se encuentran detalles", "Error",JOptionPane.ERROR_MESSAGE);
                   // tf_valor.setText(null);
                    return;
                }
                else{
        for(i=0;i<oc.size();i++){
            valor= oc.get(i).getCodDetalle();
            DetalleOrdenCompra tc3 = obtenerArticulos(valor);
            DetalleFacturacompra fa3= obtenerDetalleFactura(Integer.parseInt(txt_num3.getText()));
            codigo= tc3.getCodArticulo().getCodigoArticulo();
            cantidadRecibida =fa3.getCantidad();// tc3.getCantidadRecibida();
            cantidadPedida= tc3.getCantidadPedida();
            nombreArticulo = tc3.getCodArticulo().getNombre();
            precio = tc3.getCodArticulo().getCosto();
            tf_proveedor.setText(tc3.getCodProveedor().getRazonSocial());
            totalCompra = precio*cantidadRecibida;
            inicializar_factura_compra(nombreArticulo, precio, cantidadPedida,cantidadRecibida, codigo);
                }
                }
    }

   
public  static void inicializar_factura_compra(String art, int precio, int cantPedida, int cantRecibida, int codArt) {
        
        DefaultTableModel dtmCompra = (DefaultTableModel) tablaCompra.getModel();
       /* String[] fila = new String[5];
        fila[0] = String.valueOf(codArt);
        fila[1]= art;
        fila[2] = String.valueOf(precio);
        fila[3] = String.valueOf(cant);
        fila[4] = String.valueOf(precio*cant);*/
        
         String[] fila = new String[5];
        fila[0] = art;
      //  fila[1]= art;
        fila[1] = String.valueOf(precio);
        fila[2] = String.valueOf(cantPedida);
        fila[3] = String.valueOf(cantRecibida);
        fila[4] = String.valueOf(precio*cantRecibida);
        
        
        dtmCompra.addRow(fila);
        tablaCompra.setModel(dtmCompra);
        
        totaliva = (Integer.parseInt(txtIva.getText())+((precio*cantRecibida)/11));
        totalCompra = (Integer.parseInt(txt_total.getText()) +(precio*cantRecibida) );
        txt_total.setText("" + totalCompra);
      txtIva.setText("" + totaliva);
}
public static void vaciar_tabla_factura_compra() {
        tablaCompra.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{
                     "Descripcion", "Precio", "Cantidad Pedida","Cantidad Recibida","Total" 
                }) {

            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        txt_total.setText("0");
        tablaCompra.getTableHeader().setReorderingAllowed(false);
       
    }
public static void vaciar() {
        vaciar_tabla_factura_compra();
        txt_total.setText("0");
        tablaCompra.getTableHeader().setReorderingAllowed(false);
        txtIva.setText("0");
       tf_oc.setText("");
       txt_num1.setText("");
       txt_num2.setText("");
       txt_num3.setText("");
       tf_proveedor.setText("");
       jf_fechaF.setDate(null);
       jf_fechaI.setDate(null);
    }


    public static AuditoriaSistema registrarAuditoria(String accion,String tab, String datos){
         AuditoriaSistema as=new AuditoriaSistema();
                    as.setAccion(accion);
                    as.setTabla(tab);
                    as.setAntes(datos);
                    as.setDespues("No hay cambios");
                     //trabajamos con la fecha
                    Date fechaAuditoria=new Date();
                    DateFormat formato1=new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
                    as.setFechaHora((formato1.format(fechaAuditoria)));
                    as.setUsuario(LoginView.nombreUsuario);
                    return as;
    }
    private void imprimir(int numero) {
     
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel db", "root", "1234");
            HashMap par = new HashMap();//no definimos ningún parámetro por eso lo dejamos así
           // Map parametros=new HashMap();
            par.put("NumeroFactura",numero );
            JasperPrint jp = JasperFillManager.fillReport("C:/proyecto/src/reportes/FacturaCompra_1_1.jasper", par,con);//el primer parámetro es el camino del archivo, se cambia esta dirección por la dirección del archivo .jasper
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setVisible(true);
            jv.setTitle("Informe Recepcion");
         //    Image icon = new ImageIcon(getClass().getResource("/imagenes/hotel2.png")).getImage();
           //  jv.setIconImage(icon);
            jv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
         }

    
}
