/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import bean.AuditoriaSistema;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;

/**
 *
 * @author Jorge
 */
public class MenuRecepcionista extends javax.swing.JFrame {
     public static int opcion=0;
    

    /**
     * Creates new form MenuRecepcionista
     */
    public MenuRecepcionista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_cliente = new javax.swing.JMenu();
        mItem_crearC = new javax.swing.JMenuItem();
        mItem_editarC = new javax.swing.JMenuItem();
        mItem_eliminarC = new javax.swing.JMenuItem();
        mItem_buscarC = new javax.swing.JMenuItem();
        menu_reserva = new javax.swing.JMenu();
        mItem_registrarReserva = new javax.swing.JMenuItem();
        mItem_editarReserva = new javax.swing.JMenuItem();
        mItem_eliminarReserva = new javax.swing.JMenuItem();
        mItem_buscarReserva2 = new javax.swing.JMenuItem();
        mItem_contrato = new javax.swing.JMenuItem();
        menu_consumo2 = new javax.swing.JMenu();
        mItem_registrarConsumo2 = new javax.swing.JMenuItem();
        mItem_modificarConsumo = new javax.swing.JMenuItem();
        mItem_eliminarConsumo = new javax.swing.JMenuItem();
        mItem_buscarConsumo = new javax.swing.JMenuItem();
        menu_resumen = new javax.swing.JMenu();
        menu_factura = new javax.swing.JMenu();
        mItem_generarFactura = new javax.swing.JMenuItem();
        mItem_buscarFactura = new javax.swing.JMenuItem();
        menu_presupuesto = new javax.swing.JMenu();
        menu_salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_cliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.png"))); // NOI18N
        menu_cliente.setText(" Clientes");
        menu_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_clienteActionPerformed(evt);
            }
        });

        mItem_crearC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-student.png"))); // NOI18N
        mItem_crearC.setText("Registrar Cliente");
        mItem_crearC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_crearCActionPerformed(evt);
            }
        });
        menu_cliente.add(mItem_crearC);

        mItem_editarC.setText("Editar Cliente");
        mItem_editarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_editarCActionPerformed(evt);
            }
        });
        menu_cliente.add(mItem_editarC);

        mItem_eliminarC.setText("Eliminar Cliente");
        mItem_eliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_eliminarCActionPerformed(evt);
            }
        });
        menu_cliente.add(mItem_eliminarC);

        mItem_buscarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        mItem_buscarC.setText("Buscar Cliente");
        mItem_buscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_buscarCActionPerformed(evt);
            }
        });
        menu_cliente.add(mItem_buscarC);

        jMenuBar1.add(menu_cliente);

        menu_reserva.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_reserva.setText(" Reservas");
        menu_reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_reservaActionPerformed(evt);
            }
        });

        mItem_registrarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-student.png"))); // NOI18N
        mItem_registrarReserva.setText("Registrar Reserva");
        mItem_registrarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_registrarReservaActionPerformed(evt);
            }
        });
        menu_reserva.add(mItem_registrarReserva);

        mItem_editarReserva.setText("Editar Reserva");
        mItem_editarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_editarReservaActionPerformed(evt);
            }
        });
        menu_reserva.add(mItem_editarReserva);

        mItem_eliminarReserva.setText("Eliminar Reserva");
        mItem_eliminarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_eliminarReservaActionPerformed(evt);
            }
        });
        menu_reserva.add(mItem_eliminarReserva);

        mItem_buscarReserva2.setText("Buscar Reserva");
        mItem_buscarReserva2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_buscarReserva2ActionPerformed(evt);
            }
        });
        menu_reserva.add(mItem_buscarReserva2);

        mItem_contrato.setText("Generar Contrato de Reserva");
        mItem_contrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_contratoActionPerformed(evt);
            }
        });
        menu_reserva.add(mItem_contrato);

        jMenuBar1.add(menu_reserva);

        menu_consumo2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_consumo2.setText("Consumos");

        mItem_registrarConsumo2.setText("Registrar Consumo");
        mItem_registrarConsumo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_registrarConsumo2ActionPerformed(evt);
            }
        });
        menu_consumo2.add(mItem_registrarConsumo2);

        mItem_modificarConsumo.setText("Modificar Consumo");
        mItem_modificarConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_modificarConsumoActionPerformed(evt);
            }
        });
        menu_consumo2.add(mItem_modificarConsumo);

        mItem_eliminarConsumo.setText("Eliminar Consumo");
        mItem_eliminarConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_eliminarConsumoActionPerformed(evt);
            }
        });
        menu_consumo2.add(mItem_eliminarConsumo);

        mItem_buscarConsumo.setText("Buscar Consumo");
        mItem_buscarConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_buscarConsumoActionPerformed(evt);
            }
        });
        menu_consumo2.add(mItem_buscarConsumo);

        jMenuBar1.add(menu_consumo2);

        menu_resumen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_resumen.setText("Ver Resumen de Consumo");
        menu_resumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_resumenMouseClicked(evt);
            }
        });
        menu_resumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_resumenActionPerformed(evt);
            }
        });
        jMenuBar1.add(menu_resumen);

        menu_factura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dinero.png"))); // NOI18N
        menu_factura.setText("Facturas de Cobro");
        menu_factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_facturaMouseClicked(evt);
            }
        });

        mItem_generarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/table.png"))); // NOI18N
        mItem_generarFactura.setText("Generar Factura");
        mItem_generarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_generarFacturaActionPerformed(evt);
            }
        });
        menu_factura.add(mItem_generarFactura);

        mItem_buscarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        mItem_buscarFactura.setText("Buscar Facturas");
        mItem_buscarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_buscarFacturaActionPerformed(evt);
            }
        });
        menu_factura.add(mItem_buscarFactura);

        jMenuBar1.add(menu_factura);

        menu_presupuesto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_presupuesto.setText("Generar Presupuesto");
        menu_presupuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_presupuestoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_presupuesto);

        menu_salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excluded.png"))); // NOI18N
        menu_salir.setText("Cerrar Sesión");
        menu_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_salirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_clienteActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_menu_clienteActionPerformed

    private void mItem_crearCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_crearCActionPerformed
        // TODO add your handling code here:
        String args[]=new String[1];
        args[0]="Registrar Cliente";
        ClienteCreate.main(args);
    }//GEN-LAST:event_mItem_crearCActionPerformed

    private void mItem_eliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_eliminarCActionPerformed
        // TODO add your handling code here:
         opcion=2;
        String args[]=new String[1];
        args[0]="Buscar Cliente";
        ClienteBuscar.main(args);
    }//GEN-LAST:event_mItem_eliminarCActionPerformed

    private void mItem_editarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_editarCActionPerformed
        // TODO add your handling code here:
        opcion=1;
        String args[]=new String[1];
        args[0]="Buscar Cliente";
        ClienteBuscar.main(args);
    }//GEN-LAST:event_mItem_editarCActionPerformed

    private void mItem_buscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_buscarCActionPerformed
        // TODO add your handling code here:
         opcion=3;
        String args[]=new String[1];
        args[0]="Buscar Cliente";
        ClienteBuscar.main(args);
    }//GEN-LAST:event_mItem_buscarCActionPerformed

    private void menu_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_salirMouseClicked
        // TODO add your handling code here:
           EntityManagerFactory fact=Persistence.createEntityManagerFactory("proyectoPU");
            EntityManager ema= fact.createEntityManager();
            ema.getTransaction().begin();
            //registramos los datos necesarios para la auditoria
            AuditoriaSistema as=new AuditoriaSistema();
            as.setAccion("Cerro Sesion");
            as.setTabla("Ninguna");
            //trabajamos con la fecha
            Date fecha=new Date();
            DateFormat formato=new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
            as.setFechaHora(formato.format(fecha));
            as.setUsuario(LoginView.nombreUsuario);
            ema.persist(as);
            ema.getTransaction().commit();
            ema.close();
            this.dispose();
            String args[]=new String[1];
            args[0]="Ingreso al sistema";
            LoginView.main(args);
                                  
    }//GEN-LAST:event_menu_salirMouseClicked

    private void mItem_registrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_registrarReservaActionPerformed
        // TODO add your handling code here:
        String args[]=new String[1];
        args[0]="Registrar Reserva";
        CrearReserva.main(args);
        
    }//GEN-LAST:event_mItem_registrarReservaActionPerformed

    private void menu_reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_reservaActionPerformed
        // TODO add your handling code here:
        JFrame frame=new ConsumoResumen();
        frame.setVisible(true);
        frame.setTitle("Lista de Reservas");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_menu_reservaActionPerformed

    private void mItem_editarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_editarReservaActionPerformed
        // TODO add your handling code here:
        opcion = 1;
        String args[] = new String[1];
        args[0] = "Editar Reserva";
        BuscarReserva.main(args);
    }//GEN-LAST:event_mItem_editarReservaActionPerformed

    private void mItem_eliminarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_eliminarReservaActionPerformed
        // TODO add your handling code here:
        opcion = 2;
        String args[] = new String[1];
        args[0] = "Eliminar Reserva";
        BuscarReserva.main(args);
    }//GEN-LAST:event_mItem_eliminarReservaActionPerformed

    private void mItem_buscarReserva2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_buscarReserva2ActionPerformed
        // TODO add your handling code here:
        opcion = 3;
        String args[] = new String[1];
        args[0] = "Buscar Reserva";
        BuscarReserva.main(args);
    }//GEN-LAST:event_mItem_buscarReserva2ActionPerformed

    private void mItem_registrarConsumo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_registrarConsumo2ActionPerformed
        // TODO add your handling code here:
        String args[]=new String[1];
        args[0]="Registrar Consumo de Producto/Servicio";
        ConsumoPSCreate.main(args);
    }//GEN-LAST:event_mItem_registrarConsumo2ActionPerformed

    private void mItem_modificarConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_modificarConsumoActionPerformed
        // TODO add your handling code here:
        opcion=1;
        String args[]=new String[1];
        args[0]="Buscar Consumo de Producto/Servicio";
        BuscarConsumoPS.main(args);
    }//GEN-LAST:event_mItem_modificarConsumoActionPerformed

    private void mItem_eliminarConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_eliminarConsumoActionPerformed
        // TODO add your handling code here:
        opcion=2;
        String args[]=new String[1];
        args[0]="Buscar Consumo de Producto/Servicio";
        BuscarConsumoPS.main(args);
    }//GEN-LAST:event_mItem_eliminarConsumoActionPerformed

    private void mItem_buscarConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_buscarConsumoActionPerformed
        // TODO add your handling code here:
        opcion=3;
        String args[]=new String[1];
        args[0]="Buscar Consumo de Producto/Servicio";
        BuscarConsumoPS.main(args);
    }//GEN-LAST:event_mItem_buscarConsumoActionPerformed

    private void menu_resumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_resumenActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_menu_resumenActionPerformed

    private void menu_resumenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_resumenMouseClicked
        // TODO add your handling code here:
        String args[]=new String[1];
        args[0]="Resumen de consumo del cliente";
        ConsumoResumen.main(args);
       
    }//GEN-LAST:event_menu_resumenMouseClicked

    private void menu_facturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_facturaMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_menu_facturaMouseClicked

    private void mItem_generarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_generarFacturaActionPerformed
        // TODO add your handling code here:
          JFrame frame=new ConsumoFactura();
        frame.setVisible(true);
        frame.setTitle("Generar Factura de cliente");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_mItem_generarFacturaActionPerformed

    private void mItem_buscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_buscarFacturaActionPerformed
        // TODO add your handling code here:
        JFrame frame=new BuscarFacturaCobro();
        frame.setVisible(true);
        frame.setTitle("Buscar Factura de Cobro");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_mItem_buscarFacturaActionPerformed

    private void menu_presupuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_presupuestoMouseClicked
        // TODO add your handling code here:
         String args[]=new String[1];
        args[0]="Generar Presupuesto";
        Presupuesto.main(args);
    }//GEN-LAST:event_menu_presupuestoMouseClicked

    private void mItem_contratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_contratoActionPerformed
        // TODO add your handling code here:
          JFrame frame=new GenerarContrato();
          frame.setVisible(true);
          frame.setTitle("Generar Contrato de Reserva");
          frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
          frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_mItem_contratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame=new MenuRecepcionista();
                frame.setTitle("Menu Recepcionista");
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mItem_buscarC;
    private javax.swing.JMenuItem mItem_buscarConsumo;
    private javax.swing.JMenuItem mItem_buscarFactura;
    private javax.swing.JMenuItem mItem_buscarReserva2;
    private javax.swing.JMenuItem mItem_contrato;
    private javax.swing.JMenuItem mItem_crearC;
    private javax.swing.JMenuItem mItem_editarC;
    private javax.swing.JMenuItem mItem_editarReserva;
    private javax.swing.JMenuItem mItem_eliminarC;
    private javax.swing.JMenuItem mItem_eliminarConsumo;
    private javax.swing.JMenuItem mItem_eliminarReserva;
    private javax.swing.JMenuItem mItem_generarFactura;
    private javax.swing.JMenuItem mItem_modificarConsumo;
    private javax.swing.JMenuItem mItem_registrarConsumo2;
    private javax.swing.JMenuItem mItem_registrarReserva;
    private javax.swing.JMenu menu_cliente;
    private javax.swing.JMenu menu_consumo2;
    private javax.swing.JMenu menu_factura;
    private javax.swing.JMenu menu_presupuesto;
    private javax.swing.JMenu menu_reserva;
    private javax.swing.JMenu menu_resumen;
    private javax.swing.JMenu menu_salir;
    // End of variables declaration//GEN-END:variables
}
